### PR TITLE
Fix race condition after stopping service and trying to add an item to the channel

### LINKED ISSUE #5: Race condition when stop service
**Describe the bug**

Basically, when restarting the Service when other goroutines try to send requests a race condition occurs.

**To Reproduce**

1. Start the service
2. Open a goroutine to use the service instance
3. Stop the instance
4. Start again

**Expected behavior**

None race condition should happen when restarting a Service. Ideally the New factory of the sync.RWMutex should be set once for the instance (not on every start).

### PR DESCRIPTION
**Pull request by edumarcal**
### :bug: Bugs

* Correct the race condition after stopping service and trying to add an item to the channel.

---

Fix: #5

### CODE REVIEW

File: producer_channel.go [hunk 1]
```diff
@@ -6,24 +6,32 @@ import "sync"
...
 func NewChannelProducer(cap int) *ChannelProducer {
 	return &ChannelProducer{
 		shutdown: make(chan struct{}),
-		Ch:       make(chan interface{}, cap),
+		ch:       make(chan interface{}, cap),
 	}
 }
 
+// Produce store data on the channel.
+func (producer *ChannelProducer) Produce(data interface{}) {
```
Comment (felipemfp) [inline producer_channel.go]:
```suggestion
// Yield sends data though the channel to be produced in the Pool.
func (producer *ChannelProducer) Yield(data interface{}) {
```

**Review by felipemfp — APPROVED** [review]
Everything looks good! I just think the name `.Yield` ([as in a generator](https://en.wikipedia.org/wiki/Generator_(computer_programming))) says more about what is actually happening than `.Produce`.
